ALTER TABLE student MODIFY COLUMN birthday DATE NOT NULL;
ALTER TABLE mark MODIFY COLUMN mark INT NOT NULL CHECK (mark BETWEEN 1 AND 10);
ALTER TABLE mark MODIFY COLUMN student_id BIGINT NOT NULL;
ALTER TABLE mark MODIFY COLUMN subject_id BIGINT NOT NULL;
ALTER TABLE subject ADD CONSTRAINT subjectcheck CHECK (grade BETWEEN 1 AND 10);
ALTER TABLE paymenttype MODIFY COLUMN name VARCHAR(250) UNIQUE;
ALTER TABLE payment MODIFY COLUMN type_id BIGINT NOT NULL;
ALTER TABLE payment MODIFY COLUMN amount decimal NOT NULL;
ALTER TABLE payment MODIFY COLUMN payment_date DateTime NOT NULL;